

function copiarTexto() {
    const input = document.getElementById("idteste");

    // Seleciona o texto dentro do input
    input.select();
    input.setSelectionRange(0, 99999); // Para compatibilidade com dispositivos móveis

    // Copia o texto para a área de transferência
    navigator.clipboard.writeText(input.value)
        .then(() => alert("Texto copiado com sucesso!"))
        .catch(err => console.error("Erro ao copiar texto:", err));
}



  function mostrarCarregamento() {
    document.getElementById("loading-screen").style.display = "flex";
}

function ocultarCarregamento() {
    document.getElementById("loading-screen").style.display = "none";
}




function showText() {
atualizardados2();


const nome = localStorage.getItem("nome");
  console.log(`Nome: ${nome}`);
  document.getElementById("titulopag").textContent =  nome

if (nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ASSISTIDO NÃO LOCALIZADO") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ASSISTIDO NÃO LOCALIZADO" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), PROCURAMOS POR *********, RG: *********, (PARA NOTIFICÁ-LO SOBRE SUA INCLUSÃO NO SERVIÇO DEVIDO AO REGISTRO DA OCORRÊNCIA Nº *********, REGISTRADO EM SEU DESFAVOR POR SUA (EX-)COMPANHEIRA, *********, RG *********.)  (PARA APRESENTÁ-LO A LEI 11.340/2006 (LEI MARIA DA PENHA), DEVIDO AO MONITORAMENTO DO CASO ENVOLVENDO ELE E SUA (EX-)COMPANHEIRA, *********, *********.) (PARA MONITORAR O CASO ENVOLVENDO ELE E SUA (EX-)COMPANHEIRA, *********, RG *********.)" +  "\n\n"  + 
  " ESTA EQUIPE NÃO OBTEVE ÊXITO EM LOCALIZAR O ASSISTIDO. AINDA TENTAMOS CONTATO TELEFÔNICO ATRAVÉS DO NÚMERO *********, MAS A LIGAÇÃO FOI DIRECIONADA PARA A CAIXA POSTAL." +  "\n\n" +
  " DESSA FORMA, SERÃO REALIZADAS NOVAS TENTATIVAS DE CONTATO COM O INTUITO DE DAR PROSSEGUIMENTO AO PROTOCOLO DE ATENDIMENTO DO ASSISTIDO NO SERVIÇO DE PREVENÇÃO A VIOLÊNCIA DOMÉSTICA."

}


if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ASSISTIDA NÃO LOCALIZADA") {
document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ASSISTIDA NÃO LOCALIZADA" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), PROCURAMOS POR *********, RG: *********,, (PARA INCLUÍ-LA NO SERVIÇO DEVIDO AO REGISTRO DA OCORRÊNCIA Nº *********, EM DESFAVOR DE SEU (EX-)COMPANHEIRO, *********, RG *********. (PARA APRESENTÁ-LA A LEI 11.340/2006 (LEI MARIA DA PENHA), DEVIDO AO MONITORAMENTO DO CASO ENVOLVENDO ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. (PARA MONITORAR O CASO ENVOLVENDO ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. (PARA ENCERRAR O MONITORAMENTO DO CASO ENVOLVENDO ELA E SEU (EX-)COMPANHEIRO, *********, RG *********.)" +  "\n\n"  + 
  " ESTA EQUIPE NÃO OBTEVE ÊXITO EM LOCALIZAR A ASSISTIDA. AINDA TENTAMOS CONTATO TELEFÔNICO ATRAVÉS DO NÚMERO *********, MAS A LIGAÇÃO FOI DIRECIONADA PARA A CAIXA POSTAL." +  "\n\n" +
  " DESSA FORMA, SERÃO REALIZADAS NOVAS TENTATIVAS DE CONTATO COM O INTUITO DE DAR PROSSEGUIMENTO AO PROTOCOLO DE ATENDIMENTO DA ASSISTIDA NO SERVIÇO DE PREVENÇÃO A VIOLÊNCIA DOMÉSTICA."
}


if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: INCLUSÃO DA VÍTIMA E AVALIAÇÃO DE RISCO") {
document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: INCLUSÃO DA VÍTIMA E AVALIAÇÃO DE RISCO" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA INCLUÍ-LA NO SERVIÇO DEVIDO AO REGISTRO DA OCORRÊNCIA Nº *********, EM DESFAVOR DE SEU (EX-) COMPANHEIRO, *********, RG *********." +  "\n\n"  + 
  " A ASSISTIDA INFORMOU QUE: RELACIONA-SE (RELACIONOU-SE) COM O ASSISTIDO (POR) HÁ *********; (NÃO) RESIDEM NO MESMO IMÓVEL; (ESTÃO SEPARADOS HÁ *********); (NÃO) POSSUEM ********* FILHOS EM COMUM; REGISTROU ********* BOLETINS DE OCORRÊNCIA, EM VIRTUDE DE VIOLÊNCIA DOMÉSTICA; (NÃO) POSSUI MEDIDAS PROTETIVAS; O ASSISTIDO (NÃO) POSSUI ARMA DE FOGO." +  "\n\n" +
  " ********* RESSALTOU QUE ********* JÁ COMETEU AGRESSÕES PSICOLÓGICAS ATRAVÉS DE *********; AGRESSÕES FÍSICAS ATRAVÉS DE *********; AGRESSÕES SEXUAIS ATRAVÉS DE *********; AGRESSÕES MORAIS ATRAVÉS DE *********; E AGRESSÕES PATRIMONIAIS AO *********. ELE FAZ (NÃO FAZ) USO DE BEBIDA ALCOÓLICA E DE DROGAS. ALÉM DISSO, O ASSISTIDO JÁ AMEAÇOU SUICIDAR-SE E PRATICOU AS VIOLÊNCIAS NA PRESENÇA DAS CRIANÇAS. A ASSISTIDA APRESENTOU AS MEDIDAS PROTETIVAS, PROCESSO Nº *********, REFERENTE AO ********* JUIZADO DE VIOLÊNCIA DOMÉSTICA, EXPEDIDAS EM **/**/**, DISSE QUE ESTÁ TUDO BEM E QUE NÃO VOLTOU A TER NOVOS PROBLEMAS. (OU, A ASSISTIDA INFORMOU QUE NÃO SOLICITOU MEDIDAS PROTETIVAS EM DESFAVOR DO ASSISTIDO, ALEGANDO QUE NÃO HOUVE NECESSIDADE). (OU, A ASSISTIDA INFORMOU QUE SOLICITOU MEDIDAS PROTETIVAS E ESTÁ AGUARDANDO INTIMAÇÃO)." +  "\n\n" + " ********* ASSINOU O TERMO DE INCLUSÃO E FOI ORIENTADA SOBRE AS PROVIDÊNCIAS A SEREM ADOTADAS DIANTE DE NOVOS EPISÓDIOS DE VIOLÊNCIA."+  "\n\n" + " DAREMOS CONTINUIDADE AO MONITORAMENTO DO CASO." +  "\n\n" + " REDS RELACIONADOS AO CASO: *********"
}


//PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ENCAMINHAMENTO

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ENCAMINHAMENTO") {
document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ENCAMINHAMENTO" + "\n\n" + " DURANTE VISITA (DE INCLUSÃO DA VÍTIMA NO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD)/ DE MONITORAMENTO DA VÍTIMA/ DE APRESENTAÇÃO DA LEI PARA A VÍTIMA/ DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REFERENTE AO CASO DE VIOLÊNCIA DOMÉSTICA ENVOLVENDO *********, RG *********, E *********, RG *********, FOI OBSERVADA A NECESSIDADE DE ENCAMINHAR A ASSISTIDA *********." + "\n\n"+ " ********* CONCORDOU COM O ENCAMINHAMENTO E ENTRARÁ EM CONTATO COM O ÓRGÃO PARA VERIFICAR AS CONDIÇÕES DE ATENDIMENTO. INSTA OBSERVAR QUE A EQUIPE ORIENTOU A ASSISTIDA, EXAUSTIVAMENTE, ACERCA DA DISPONIBILIDADE DOS ÓRGÃOS DE APOIO A MULHER, INFORMANDO-A DE QUE ELES PODERÃO SER ACIONADOS CONFORME O CASO EXIGIR OU ELA JULGUE NECESSÁRIO, E DA IMPORTÂNCIA DA ARTICULAÇÃO ENTRE AS INSTITUIÇÕES PARA DESESTIMULAR AS AÇÕES VIOLENTAS DO AGRESSOR. DESSA FORMA, FORNECEMOS A ELA UMA LISTA COM OS ENDEREÇOS E TELEFONES DOS PRINCIPAIS ÓRGÃOS DA REDE." +  "\n\n"  + " A ASSISTIDA ASSINOU O TERMO DE ENCAMINHAMENTO." +  "\n\n"  + " DAREMOS SEQUÊNCIA AO MONITORAMENTO. (O CASO NÃO SERÁ MONITORADO, POIS ********* RECUSOU SUA INCLUSÃO NO SPVD.)" + "\n\n" + "/////////FIM/////////" + "\n\n" + " SEGUE ALGUNS EXEMPLOS DE ÓRGÃOS PARA ENCAMINHAMENTO:" + "\n\n" + "- PARA A DELEGACIA ESPECIALIZADA NO ATENDIMENTO À MULHER (DEAM) PARA SOLICITAR MEDIDAS PROTETIVAS DE URGÊNCIA" + "\n"  + "- PARA O CENTRO RISOLETA NEVES DE ATENDIMENTO ÀS MULHERES VÍTIMAS DE VIOLÊNCIA DOMÉSTICA OU INTRAFAMILIAR (CERNA) PARA RECEBER ACOMPANHAMENTO PSICOSSOCIAL." + "\n" + "- PARA A DEFENSORIA PÚBLICA – NÚCLEO DE DEFESA DA MULHER (NUDEM) PARA RECEBER APOIO JURÍDICO." + "\n" + "- PARA O CENTRO ESPECIALIZADO DE ATENDIMENTO À MULHER (BENVINDA) PARA RECEBER ACOMPANHAMENTO PSICOSSOCIAL" + "\n" +
"- PARA O ***º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER PARA OBTER CÓPIA DA DECISÃO QUE DEFERIU MEDIDAS PROTETIVAS EM SEU FAVOR." + '\n' + "- PARA A UNIDADE GESTORA DE MONITORAÇÃO ELETRÔNICA (UGME) PARA BUSCAR A UNIDADE PORTÁTIL DE RASTREAMENTO REFERENTE AO MONITORAMENTO ELETRÔNICO DO SEU EX-COMPANHEIRO - PARA A PROMOTORIA DE JUSTIÇA ESPECIALIZADA NO COMBATE À VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER."

}


//PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ENCAMINHAMENTO

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: RECUSA DE ENCAMINHAMENTO") {
document.getElementById("idteste").value =" PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: RECUSA DE ENCAMINHAMENTO" + "\n\n" + " DURANTE VISITA (DE INCLUSÃO DA VÍTIMA NO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD)/ DE MONITORAMENTO DA VÍTIMA/ DE APRESENTAÇÃO DA LEI PARA A VÍTIMA/ DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REFERENTE AO CASO DE VIOLÊNCIA DOMÉSTICA ENVOLVENDO *********, RG *********, E *********, RG *********, FOI OBSERVADA A NECESSIDADE DE ENCAMINHAR A ASSISTIDA *********." + "\n\n" + " APESAR DA EQUIPE RESSALTAR A IMPORTÂNCIA DE BUSCAR O APOIO DO ÓRGÃO, ********* RECUSOU O ENCAMINHAMENTO E ALEGOU QUE *********. INSTA OBSERVAR QUE A EQUIPE ORIENTOU A ASSISTIDA, EXAUSTIVAMENTE, ACERCA DA DISPONIBILIDADE DOS ÓRGÃOS DE APOIO A MULHER, INFORMANDO-A DE QUE ELES PODERÃO SER ACIONADOS CONFORME O CASO EXIGIR OU ELA JULGUE NECESSÁRIO, E DA IMPORTÂNCIA DA ARTICULAÇÃO ENTRE AS INSTITUIÇÕES PARA DESESTIMULAR AS AÇÕES VIOLENTAS DO AGRESSOR E/OU AUXILIÁ-LA DURANTE O PROCESSO DE FORTALECIMENTO PSICOLÓGICO E DA QUEBRA DO CICLO DA VIOLÊNCIA CONJUGAL. DESSA FORMA, FORNECEMOS A ELA UMA LISTA COM OS ENDEREÇOS E TELEFONES DOS PRINCIPAIS ÓRGÃOS DA REDE." + "\n\n" + " DIANTE DA RECUSA EM SER ENCAMINHADA, ELA ASSINOU O TERMO DE ENCAMINHAMENTO QUE SERÁ ARQUIVADO NA PASTA DO CASO." + "\n\n" + " DAREMOS SEQUÊNCIA AO MONITORAMENTO. (O CASO NÃO SERÁ MONITORADO, POIS ********* RECUSOU SUA INCLUSÃO NO SPVD.)"

}

if (nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: NOTIFICAÇÃO DO AUTOR") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: NOTIFICAÇÃO DO AUTOR" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA NOTIFICÁ-LO SOBRE SUA INCLUSÃO NO SPVD DEVIDO AO REDS Nº *********, REGISTRADO EM SEU DESFAVOR POR SUA (EX-) COMPANHEIRA, *********, RG *********." + "\n\n" + " DURANTE O CONTATO PESSOAL COM *********, A EQUIPE REALIZOU A NOTIFICAÇÃO FORMAL SOBRE SUA INSERÇÃO NO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA DA PMMG." + "\n\n" + " O ASSISTIDO INFORMOU QUE: (NÃO) FAZ USO DE BEBIDA ALCOÓLICA; (NÃO) FAZ USO DE DROGAS; (NÃO) POSSUI ANTECEDENTES CRIMINAIS; TEM CONHECIMENTO DE ********* BOLETINS DE OCORRÊNCIA COM A ASSISTIDA; E (NÃO) POSSUI ARMA DE FOGO." + "\n\n"  + " SOBRE OS FATOS QUE CULMINARAM NO REGISTRO DA OCORRÊNCIA, QUE MOTIVARAM O ACOMPANHAMENTO DO CASO, O ASSISTIDO RELATOU QUE NUNCA COMETEU VIOLÊNCIA DOMÉSTICA, TAMPOUCO AMEAÇOU A ASSISTIDA, QUE OS FATOS NARRADOS PELA ASSISTIDA SÃO MENTIRAS, QUE ELA TEM O INTERESSE EM PREJUDICÁ-LO. RELATOU QUE O CASAL JÁ TEVE ALGUNS CONFLITOS E DISCUSSÕES." + "\n\n" + " ********* INFORMOU QUE (NÃO) FOI INTIMADO DAS MEDIDAS PROTETIVAS QUE PESAM EM SEU DESFAVOR, ALEGOU QUE ESTÁ CUMPRINDO CORRETAMENTE E ESTÁ MORANDO EM OUTRA RESIDÊNCIA. AFIRMOU QUE O CASAL NÃO CHEGOU A TER UMA CONVERSA DEFINITIVA A RESPEITO DO DIVORCIO, CONTUDO REITEROU QUE IRÁ AGUARDAR TODO O DESFECHO JUDICIAL E CUMPRIRÁ CORRETAMENTE AS MEDIDAS." + "\n\n" + " ORIENTAMO-LO A RESPEITO DO CICLO DA VIOLÊNCIA DOMÉSTICA E SOBRE A IMPORTÂNCIA DE ROMPIMENTO DESTE CICLO, BEM COMO SOBRE O FUNCIONAMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA PREVISTAS NA LEI Nº 11.340/2006 (LEI MARIA DA PENHA). TAMBÉM FOI INFORMADO QUE, POSTERIORMENTE, SERÃO REALIZADAS NOVAS VISITAS PARA ELE, COM O INTUITO DE CONTINUAR A APLICAÇÃO DO PROTOCOLO." + "\n\n" + " ********* ASSINOU O TERMO DE NOTIFICAÇÃO DE INSERÇÃO NO SPVD E RECEBEU UMA CÓPIA DO REFERIDO TERMO." + " A EQUIPE CONTINUARÁ MONITORANDO O CASO."

}

if (nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: RECUSA DA VÍTIMA") {
  document.getElementById("idteste").value = "PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: RECUSA DA VÍTIMA" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA INCLUÍ-LA NO SERVIÇO DEVIDO AO REGISTRO DA OCORRÊNCIA Nº *********, ENVOLVENDO ELA E SEU (EX-) COMPANHEIRO, *********, RG *********." + "\n\n" + " A ASSISTIDA INFORMOU QUE: RELACIONA-SE (RELACIONOU-SE) COM O ASSISTIDO (POR) HÁ *********; (NÃO) RESIDEM JUNTOS; (ESTÃO SEPARADOS HÁ *********); (NÃO) POSSUEM ********* FILHOS EM COMUM; REGISTROU ********* BOLETINS DE OCORRÊNCIA CONTRA O ASSISTIDO, EM VIRTUDE DE VIOLÊNCIA DOMÉSTICA; (NÃO) POSSUI MEDIDAS PROTETIVAS; O ASSISTIDO (NÃO) POSSUI ARMA DE FOGO." + "\n\n" + " ********* RESSALTOU QUE ********* JÁ COMETEU AGRESSÕES PSICOLÓGICAS ATRAVÉS DE *********; AGRESSÕES FÍSICAS POR MEIO DE *********; AGRESSÕES SEXUAIS QUANDO *********; AGRESSÕES MORAIS ATRAVÉS DE *********; E AGRESSÕES PATRIMONIAIS AO *********. EXPLICOU AINDA QUE ELE FAZ (NÃO FAZ) USO DE BEBIDA ALCOÓLICA E DE DROGAS. ALÉM DISSO, O ASSISTIDO JÁ AMEAÇOU SUICIDAR-SE E PRATICOU AS VIOLÊNCIAS NA PRESENÇA DAS CRIANÇAS." + "\n\n" + " ********* DISSE A EQUIPE QUE REPRESENTOU CONTRA O AGRESSOR E SOLICITOU AS MEDIDAS PROTETIVAS DE URGÊNCIA Nº *********, PREVISTAS NA LEI 11.340/06 - LEI MARIA DA PENHA. AFIRMOU QUE VAI AVALIAR O AJUIZAMENTO DE AÇÃO CÍVEL PARA DEFINIR (GUARDA, VISITA, PENSÃO, DIVÓRCIO E SEPARAÇÃO DE BENS). AINDA ENFATIZOU QUE NÃO TEM INTERESSE EM SER INCLUÍDA NO SPVD DA PMMG, JUSTIFICANDO QUE A SITUAÇÃO ESTÁ TRANQUILA E QUE NÃO HÁ NECESSIDADE DO ACOMPANHAMENTO DA POLÍCIA MILITAR. (********* DISSE A EQUIPE QUE NÃO TEM INTERESSE EM REPRESENTAR CONTRA O AGRESSOR, TAMPOUCO, SOLICITAR AS MEDIDAS PROTETIVAS DE URGÊNCIA, PREVISTAS NA LEI 11.340/06 - LEI MARIA DA PENHA. DA MESMA FORMA, ELA ALEGOU NÃO TER INTERESSE EM SER INCLUÍDA NO SPVD DA PMMG, JUSTIFICANDO QUE A SITUAÇÃO ESTÁ TRANQUILA E QUE NÃO HÁ NECESSIDADE DO ACOMPANHAMENTO DA POLÍCIA MILITAR). EMBORA A ASSISTIDA TENHA RECUSADO A INTERVENÇÃO DA PMMG, A EQUIPE A APRESENTOU A LEI MARIA DA PENHA, ESCLARECENDO-A SOBRE AS FORMAS DE VIOLÊNCIA DOMÉSTICA E O CICLO DESSA VIOLÊNCIA. ELA AINDA FOI ORIENTADA A ACIONAR A PMMG E/OU COMPARECER À DELEGACIA DE ATENDIMENTO À MULHER PARA SOLICITAR PROVIDÊNCIAS CABÍVEIS, CASO O ASSISTIDO PRATIQUE NOVO ATO DE VIOLÊNCIA, BEM COMO INFORMADA DA EXISTÊNCIA DOS OUTROS ÓRGÃOS DA REDE DE ENFRENTAMENTO À VIOLÊNCIA DOMÉSTICA CONTRA A MULHER QUE PODERÃO SER ACIONADOS, CONFORME O CASO EXIGIR. ELA (NÃO) ACEITOU ENCAMINHAMENTO PARA ********* (NENHUM ÓRGÃO DA REDE DE ATENDIMENTO). FOI DISPONIBILIZADO O CONTATO DA EQUIPE PARA MAIS INFORMAÇÕES, CASO VOLTE A OCORRER NOVOS EPISÓDIOS DE VIOLÊNCIA" + "\n\n" + "********* ASSINOU O TERMO DE RECUSA DE INCLUSÃO NO SPVD E RECEBEU UMA CÓPIA DO REFERIDO TERMO." + "\n\n" + " DIANTE DA RECUSA EM SER INSERIDA NO SERVIÇO, A EQUIPE NÃO REALIZARÁ O ACOMPANHAMENTO DO CASO, A NÃO SER QUE SEJA REGISTRADO UM NOVO FATO."

}

if (nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: APRESENTAÇÃO DA LEI PARA A VÍTIMA") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: APRESENTAÇÃO DA LEI PARA A VÍTIMA" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, A QUAL ESTÁ SENDO ACOMPANHADA POR ESTA EQUIPE, DEVIDO A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********." + "\n\n" + " ESTA EQUIPE APRESENTOU PARA A ASSISTIDA OS PRINCIPAIS PONTOS DA LEI 11.340/06 - LEI MARIA DA PENHA, COM ÊNFASE NAS FORMAS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, FUNCIONAMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA E SOBRE A IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL. FOI DISCORRIDO TAMBÉM SOBRE AS SANÇÕES LEGAIS PREVISTAS NO CASO DO COMETIMENTO DE CRIMES CONTRA MULHERES, DENTRE ELAS A PREVISTA NO ART. 24-A DA REFERIDA LEI, A QUAL TIPIFICA O CRIME DE DESCUMPRIMENTO DE MEDIDAS PROTETIVAS DE URGÊNCIA IMPOSTAS EM RAZÃO DE VIOLÊNCIA DOMÉSTICA PRATICADA CONTRA MULHERES." + "\n\n" + " QUESTIONADA, ELA NOS RELATOU QUE, DESDE A ÚLTIMA VISITA REALIZADA POR ESSA GUARNIÇÃO, ********* NÃO ENTROU EM CONTATO DIRETO E ELA NÃO VOLTOU A TER NOVOS PROBLEMAS. ELA ESTÁ COM AS MEDIDAS PROTETIVAS, PROCESSO Nº *********, REFERENTE AO ********* JUIZADO DE VIOLÊNCIA DOMÉSTICA." + "\n\n" + " REITERAMOS SOBRE AS ESTRATÉGIAS DE PROTEÇÃO, A QUEM ACIONAR NO CASO DE DESCUMPRIMENTO DA MEDIDA PROTETIVA DE URGÊNCIA, BEM COMO SEMPRE ESTAR DE POSSE DE UMA CÓPIA DO DOCUMENTO. DAREMOS CONTINUIDADE AO PROTOCOLO DE ATENDIMENTO."

}

if (nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: APRESENTAÇÃO DA LEI PARA O AUTOR") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: APRESENTAÇÃO DA LEI PARA O AUTOR" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, O QUAL ESTÁ SENDO ACOMPANHADO POR ESTA EQUIPE, DEVIDO A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELE E SUA (EX-)COMPANHEIRA, *********, RG *********." + "\n\n" + " ESTA EQUIPE APRESENTOU PARA O ASSISTIDO OS PRINCIPAIS PONTOS DA LEI 11.340/06 - LEI MARIA DA PENHA, COM ÊNFASE NAS FORMAS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, ORIENTOU SOBRE O FUNCIONAMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA E SOBRE A IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL. FOI DISCORRIDO TAMBÉM SOBRE AS SANÇÕES LEGAIS PREVISTAS NO CASO DO COMETIMENTO DE CRIMES CONTRA MULHERES, DENTRE ELAS A PREVISTA NO ART. 24-A DA REFERIDA LEI, A QUAL TIPIFICA O CRIME DE DESCUMPRIMENTO DE MEDIDAS PROTETIVAS DE URGÊNCIA IMPOSTAS EM RAZÃO DE VIOLÊNCIA DOMÉSTICA PRATICADA CONTRA MULHERES." + "\n\n" + " INDAGADO SOBRE A SITUAÇÃO ATUAL COM SUA (EX-)COMPANHEIRA, ELE NOS INFORMOU QUE, APÓS SUA INCLUSÃO NO SERVIÇO, NÃO VOLTOU A TER NOVOS PROBLEMAS COM A ASSISTIDA. ACRESCENTOU AINDA QUE *********" + "\n\n" + " DAREMOS CONTINUIDADE AO PROTOCOLO DE ATENDIMENTO."

}

if (nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DA VÍTIMA") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DA VÍTIMA" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA MONITORAR A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-) COMPANHEIRO, *********, RG *********." + "\n\n" + " ********* INFORMOU QUE, APÓS SUA INCLUSÃO NO SERVIÇO, ELA NÃO VOLTOU A TER NOVOS PROBLEMAS COM O ASSISTIDO, ENFATIZANDO QUE ELE NÃO VOLTOU A PERTURBÁ-LA E QUE ESTÁ CUMPRINDO A MEDIDA PROTETIVA VIGENTE DE Nº *********, REFERENTE AO ********* JUIZADO DE VIOLÊNCIA DOMÉSTICA." + "\n\n" + " REFORÇAMOS COM A ASSISTIDA SOBRE TODAS INFORMAÇÕES REPASSADAS ANTERIORMENTE, TAIS COMO: PROVIDÊNCIAS A SEREM ADOTADAS DIANTE DE NOVOS FATOS, LEGISLAÇÕES QUE VERSAM SOBRE OS DIREITOS DAS MULHERES, O FUNCIONAMENTO DAS MEDIDAS PROTETIVAS, ÓRGÃOS QUE ATUAM NA PREVENÇÃO À VIOLÊNCIA DOMÉSTICA, ENTRE OUTROS." + "\n\n" + "DAREMOS CONTINUIDADE AO MONITORAMENTO DO CASO."

}

if (nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DO AUTOR") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DO AUTOR" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, O QUAL ESTÁ SENDO ACOMPANHADO POR ESTA EQUIPE, DEVIDO A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELE E SUA (EX-)COMPANHEIRA, *********, RG *********." + "\n\n" + " ********* INFORMOU QUE, APÓS SUA INCLUSÃO NO SERVIÇO, NÃO VOLTOU A TER NOVOS PROBLEMAS COM A ASSISTIDA, ENFATIZANDO QUE ELE ESTÁ CUMPRINDO AS MEDIDAS PROTETIVAS VIGENTES E NÃO PRETENDE REATAR O RELACIONAMENTO, MAS TÃO SOMENTE DEDICAR-SE AOS CUIDADOS DO FILHO DO CASAL." + "\n\n" + " INFORMAÇÕES IMPORTANTES REPASSADAS ANTERIORMENTE FORAM REFORÇADAS COM O ASSISTIDO, TAIS COMO: FORMAS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, FUNCIONAMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA, A IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL E SANÇÕES LEGAIS PREVISTAS NO CASO DO COMETIMENTO DE CRIMES CONTRA MULHERES." + "\n\n" + " DAREMOS CONTINUIDADE AO MONITORAMENTO DO CASO."

}

if (nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: CONTATO COM TESTEMUNHA") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: CONTATO COM TESTEMUNHA" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM A TESTEMUNHA *********, DEVIDO AO MONITORAMENTO DO CASO DE VIOLÊNCIA DOMÉSTICA ENVOLVENDO A ASSISTIDA *********, RG *********, E O ASSISTIDO *********, RG *********." + "\n\n" + " SEGUNDO *********, (IRMÃ/PAI/MÃE DA/DO ASSISTIDA /ASSISTIDO), A SITUAÇÃO ENTRE AS PARTES ESTÁ TRANQUILA E NÃO VOLTOU A OCORRER NOVOS EPISÓDIOS DE VIOLÊNCIA. RESSALTOU QUE *********. (DISPONIBILIZAMOS O CONTATO DA EQUIPE E DOS ÓRGÃOS DA REDE DE ATENDIMENTO À VIOLÊNCIA DOMÉSTICA, PARA QUE A TESTEMUNHA REPASSE PARA A (ASSISTIDA /ASSISTIDO)." + "\n\n" + " DAREMOS CONTINUIDADE AO PROTOCOLO DE ATENDIMENTO."

}

if (nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ENCERRAMENTO") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ENCERRAMENTO" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA FINALIZAR O ACOMPANHAMENTO DO CASO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********." + "\n\n" + " ********* INFORMOU QUE NÃO VOLTOU A TER NOVOS PROBLEMAS COM O ASSISTIDO, ENFATIZANDO QUE ELE NÃO VOLTOU A PERTURBÁ-LA. DISSE QUE ESTÁ COM AS MEDIDAS PROTETIVAS, PROCESSO Nº *********, REFERENTE AO *********, E DESEJA PERMANECER COM ESSE PROCESSO ATIVO PARA SUA SEGURANÇA." + "\n\n" + " DURANTE O ACOMPANHAMENTO DO CASO, ********* FOI CONTATADO E ORIENTADO EM TODOS OS PASSOS DO PROTOCOLO DO SPVD. A EQUIPE TAMBÉM FEZ CONTATO COM A TESTEMUNHA *********, QUE RATIFICOU A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA NARRADA PELA ASSISTIDA AO LONGO DO RELACIONAMENTO COM O ASSISTIDO. (DURANTE O ACOMPANHAMENTO DO CASO NÃO FOI POSSÍVEL LOCALIZAR *********, TENDO EM VISTA QUE ELE SE MUDOU E A ASSISTIDA NÃO SOUBE INFORMAR O NOVO ENDEREÇO. TAMBÉM NÃO CONSEGUIMOS NENHUM CONTATO VIA TELEFONE E NÃO FOI IDENTIFICADO NENHUM BOLETIM DE OCORRÊNCIA QUE INDICASSE O PARADEIRO DO MESMO. AINDA, (NÃO) CONSEGUIMOS NENHUM CONTATO COM FAMILIARES E AMIGOS DO REFERIDO)." + "\n\n" + " AO LONGO DO MONITORAMENTO, A ASSISTIDA TEVE INTERESSE EM SER ENCAMINHADA PELA EQUIPE PARA RECEBER ASSISTÊNCIA NO(NA) *********. ELA RECUSOU ENCAMINHAMENTOS PARA OS DEMAIS ÓRGÃOS, MAS RECEBEU AS DEVIDAS ORIENTAÇÕES SOBRE AS ATRIBUIÇÕES DE CADA UM. FOI DISPONIBILIZADO O CONTATO DA EQUIPE PARA MAIS INFORMAÇÕES. (AO LONGO DO ACOMPANHAMENTO, A ASSISTIDA NÃO TEVE INTERESSE EM SER ENCAMINHADA PARA OS ÓRGÃOS DA REDE DE ATENDIMENTO À VIOLÊNCIA DOMÉSTICA DE BELO HORIZONTE, MAS RECEBEU AS DEVIDAS ORIENTAÇÕES SOBRE AS ATRIBUIÇÕES DE CADA UM. FOI DISPONIBILIZADO O CONTATO DA EQUIPE PARA MAIS INFORMAÇÕES.)" + "\n\n" + " DIANTE DO EXPOSTO, REFORÇAMOS AS ORIENTAÇÕES COM ********* ACERCA DAS PROVIDÊNCIAS A SEREM ADOTADAS DIANTE DE NOVOS EPISÓDIOS DE VIOLÊNCIA, O FUNCIONAMENTO DAS MEDIDAS PROTETIVAS, OS DISPOSITIVOS LEGAIS QUE VERSAM SOBRE OS DIREITOS DAS MULHERES E A IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL." + "\n\n" + " POR FIM, A ASSISTIDA FOI INFORMADA QUE, APESAR DE TERMINADO SEU ACOMPANHAMENTO, ELA CONTINUARÁ A SER MONITORADA PELO SISTEMA, E, CASO HAJA NOVO REGISTRO DE OCORRÊNCIA, A EQUIPE VOLTARÁ A CONTATÁ-LA PARA A ADOÇÃO DE MEDIDAS COMPLEMENTARES." + "\n\n" + " DIANTE DA ALEGAÇÃO DA ASSISTIDA DE QUE HOUVE A QUEBRA DO CICLO DA VIOLÊNCIA DOMÉSTICA E DO CUMPRIMENTO DO PROTOCOLO DE SEGUNDA RESPOSTA DO SPVD, ESTA EQUIPE ENCERRA O ACOMPANHAMENTO DO CASO."

}

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: VISITA PARA AUTOR DE VIOLÊNCIA DOMÉSTICA") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: VISITA PARA AUTOR DE VIOLÊNCIA DOMÉSTICA" + "\n\n" + " REALIZAMOS VISITA DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD) PARA *********, RG *********, NA TENTATIVA DE LOCALIZAR *********, RG *********. AS PARTES ESTÃO ARROLADAS COMO AUTOR E VÍTIMA NO REDS Nº *********." + "\n\n" + " ********* AFIRMOU QUE: (NÃO) FAZ USO DE BEBIDA ALCOÓLICA; (NÃO) FAZ USO DE DROGAS; (NÃO) POSSUI ANTECEDENTES CRIMINAIS; TEM CONHECIMENTO DE ********* BOLETINS DE OCORRÊNCIA COM A ASSISTIDA. ********* RESSALTOU QUE AS PARTES SEMPRE TIVERAM MUITOS ATRITOS E A COMPANHEIRA É UMA PESSOA MUITO NERVOSA. RESSALTOU QUE ESTÁ TUDO BEM E QUE NÃO VOLTARAM A OCORRER NOVOS EPISÓDIOS DE VIOLÊNCIA ENTRE ELES. DISSE QUE ********* SE MUDOU (ESTAVA TRABALHANDO)." + "\n\n" + " INFORMAMOS AO ASSISTIDO SOBRE AS CONSEQUÊNCIAS DE SEUS ATOS E ACERCA DAS LEIS MARIA DA PENHA E DO FEMINICÍDIO. AINDA ENFATIZAMOS QUE, CASO OCORRA NOVOS EPISÓDIOS DE VIOLÊNCIA, DEMAIS ÓRGÃOS DA REDE DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA SERÃO INFORMADOS E O PODER JUDICIÁRIO PODERÁ DETERMINAR MEDIDAS DE PROTEÇÃO À MULHER." + "\n\n" + " DAREMOS SEQUÊNCIA AO ACOMPANHAMENTO DO CASO."
}

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: VISITA TRANQUILIZADORA À VÍTIMA DE VIOLÊNCIA DOMÉSTICA (AUTOR PRESO)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: VISITA TRANQUILIZADORA À VÍTIMA DE VIOLÊNCIA DOMÉSTICA (AUTOR PRESO)" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, DEVIDO AO REGISTRO DA OCORRÊNCIA Nº *********, EM DESFAVOR DE SEU (EX-) COMPANHEIRO, *********, RG *********." + "\n\n" + " A ASSISTIDA INFORMOU QUE: RELACIONA-SE (RELACIONOU-SE) COM O ASSISTIDO (POR) HÁ *********; (NÃO) RESIDEM JUNTOS; (ESTÃO SEPARADOS HÁ *********); (NÃO) POSSUEM ********* FILHOS EM COMUM; REGISTROU ********* BOLETINS DE OCORRÊNCIA, EM VIRTUDE DAS VIOLÊNCIAS SOFRIDAS; (NÃO) POSSUI MEDIDAS PROTETIVAS; O ASSISTIDO (NÃO) POSSUI ARMA DE FOGO." + "\n\n" + " RESSALTOU AINDA QUE ********* JÁ COMETEU AGRESSÕES PSICOLÓGICAS ATRAVÉS DE *********; AGRESSÕES FÍSICAS ATRAVÉS DE *********; AGRESSÕES SEXUAIS ATRAVÉS DE *********; AGRESSÕES MORAIS ATRAVÉS DE *********; E AGRESSÕES PATRIMONIAIS AO *********. ELE FAZ (NÃO FAZ) USO DE BEBIDA ALCOÓLICA E DE DROGAS. ALÉM DISSO, O ASSISTIDO JÁ AMEAÇOU SUICIDAR-SE E PRATICOU AS VIOLÊNCIAS NA PRESENÇA DAS CRIANÇAS." + "\n\n" + " ********* APRESENTOU AS MEDIDAS PROTETIVAS, PROCESSO Nº *********, REFERENTE AO ********* JUIZADO DE VIOLÊNCIA DOMÉSTICA, E DISSE QUE ESTÁ TUDO BEM E QUE NÃO VOLTOU A TER NOVOS PROBLEMAS COM O ASSISTIDO. (OU, A ASSISTIDA INFORMOU QUE NÃO SOLICITOU MEDIDAS PROTETIVAS EM DESFAVOR DO ASSISTIDO, ALEGANDO QUE NÃO HOUVE NECESSIDADE). (OU, A ASSISTIDA INFORMOU QUE SOLICITOU MEDIDAS PROTETIVAS E ESTÁ AGUARDANDO INTIMAÇÃO)." + "\n\n" + " ********* FOI ORIENTADA SOBRE OS PROCEDIMENTOS A SEREM ADOTADOS NO CASO DE UM NOVO EPISÓDIO DE VIOLÊNCIA OU DESCUMPRIMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA, BEM COMO INFORMADA SOBRE OS ÓRGÃOS QUE COMPÕEM A REDE DE ATENDIMENTO À MULHERES EM SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA DE BELO HORIZONTE. INICIALMENTE, ELA TEVE INTERESSE EM SER ENCAMINHADA PELA EQUIPE PARA *********. ELA RECUSOU ENCAMINHAMENTOS PARA OS DEMAIS ÓRGÃOS, MAS RECEBEU AS DEVIDAS ORIENTAÇÕES SOBRE AS ATRIBUIÇÕES DE CADA UM)." + "\n\n" + " O CASO NÃO SERÁ MONITORADO NO MOMENTO, POIS ********* (O ASSISTIDO ENCONTRA-SE PRESO, SEM PREVISÃO DE SOLTURA). DIANTE DO EXPOSTO, FOI DISPONIBILIZADO PARA A ASSISTIDA OS CONTATOS DA 1ª CIA PM IND E DA EQUIPE PARA QUE ELA INFORME SE DESEJAR SER ACOMPANHADA PELO SPVD QUANDO O ASSISTIDO FOR COLOCADO EM LIBERDADE, BEM COMO, SE, AINDA PRESO, ELE VENHA A OFERECER RISCO À INTEGRIDADE DA ASSISTIDA."

}

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: VISITA TRANQUILIZADORA À VÍTIMA DE VIOLÊNCIA DOMÉSTICA (CASO DE NÃO-CONJUGALIDADE)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: VISITA TRANQUILIZADORA À VÍTIMA DE VIOLÊNCIA DOMÉSTICA (CASO DE NÃO-CONJUGALIDADE)" + "\n\n" + " APÓS SOLICITAÇÃO DO Xº JUVID (Xº JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER), REALIZAMOS CONTATO COM *********, RG *********, PARA VERIFICAR A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA SOFRIDA POR ELA E PRATICADA POR *********, RG *********."+ "\n\n" +  " A ASSISTIDA INFORMOU QUE O ASSISTIDO É SEU FILHO; JÁ REGISTROU ********* BOLETINS DE OCORRÊNCIA, EM VIRTUDE DE VIOLÊNCIA DOMÉSTICA COMETIDA POR ELE; ELE NÃO POSSUI ARMA DE FOGO. ********* POSSUI AS MEDIDAS PROTETIVAS DE URGÊNCIA Nº *********, EXPEDIDAS PELO *********º JUIZADO DE VIOLÊNCIA DOMÉSTICA (*********º JUVID) DE BELO HORIZONTE/MG, MAS ********* CONTINUA RESIDINDO COM ELA." + "\n\n" + " RESSALTOU AINDA QUE ********* JÁ COMETEU AGRESSÕES PSICOLÓGICAS ATRAVÉS DE *********; AGRESSÕES FÍSICAS ATRAVÉS DE *********; AGRESSÕES SEXUAIS ATRAVÉS DE *********; AGRESSÕES MORAIS ATRAVÉS DE *********; E AGRESSÕES PATRIMONIAIS AO *********. ELE FAZ (NÃO FAZ) USO DE BEBIDA ALCOÓLICA E DE DROGAS. ALÉM DISSO, O ASSISTIDO JÁ AMEAÇOU SUICIDAR-SE E PRATICOU AS VIOLÊNCIAS NA PRESENÇA DE FAMILIARES." + "\n\n" + " A ASSISTIDA AINDA NOS RELATOU QUE NÃO SABE SE O ASSISTIDO FOI INTIMADO DA EXISTÊNCIA DAS MEDIDAS PROTETIVAS DE URGÊNCIA E QUE ELE NÃO ESTAVA NO LOCAL NO MOMENTO DE NOSSA VISITA" + "\n\n" + " A EQUIPE DISCORREU PARA A ASSISTIDA SOBRE A LEI 11.340/06 - LEI MARIA DA PENHA, ESCLARECENDO-A SOBRE AS FORMAS DE VIOLÊNCIA DOMÉSTICA E O CICLO DESSA VIOLÊNCIA. ELA AINDA FOI ORIENTADA A ACIONAR A PMMG E/OU COMPARECER À DELEGACIA DE ATENDIMENTO À MULHER PARA SOLICITAR PROVIDÊNCIAS CABÍVEIS, CASO O ASSISTIDO PRATIQUE NOVO ATO DE VIOLÊNCIA OU VENHA A DESCUMPRIR QUALQUER UMAS DAS MEDIDAS PROTETIVAS DE URGÊNCIA DEFERIDAS PARA O CASO." + "\n\n" + " DE IGUAL MANEIRA, FOI INFORMADA DA EXISTÊNCIA DOS OUTROS ÓRGÃOS DA REDE DE ENFRENTAMENTO À VIOLÊNCIA DOMÉSTICA CONTRA A MULHER QUE PODERÃO SER ACIONADOS, CONFORME O CASO EXIGIR." + "\n\n" + " INICIALMENTE, ELA TEVE INTERESSE EM SER ENCAMINHADA PELA EQUIPE PVD PARA RECEBER ASSISTÊNCIA NO (NA) *********. ELA RECUSOU ENCAMINHAMENTOS PARA OS DEMAIS ÓRGÃOS, MAS RECEBEU AS DEVIDAS ORIENTAÇÕES SOBRE A FUNÇÃO E OS SERVIÇOS PRESTADOS POR CADA UM." + "\n\n" + " POR NÃO SE TRATAR DE UMA RELAÇÃO DE CONJUGALIDADE, O CASO NÃO SERÁ ACOMPANHADO PELO SPVD. SERÁ CONFECCIONADO UM RELATÓRIO AO JUIZADO RESPONSÁVEL PELO PROCESSO, PARA CONHECIMENTO E PROVIDÊNCIAS JUDICIAIS."
}

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: INCLUSÃO DA VÍTIMA E AVALIAÇÃO DE RISCO (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: INCLUSÃO DA VÍTIMA E AVALIAÇÃO DE RISCO (ENVOLVENDO AUTORIDADES) " + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS VISITA À *********, RG *********, DEVIDO AO REGISTRO DA OCORRÊNCIA Nº ********* ENTRE ELA E SEU (EX-) COMPANHEIRO, *********, RG *********. " + "\n\n" + " ********* ASSINOU O TERMO DE INCLUSÃO NO SPVD E RECEBEU UMA CÓPIA DO REFERIDO TERMO. AS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES."
}

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: NOTIFICAÇÃO DO AUTOR (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: NOTIFICAÇÃO DO AUTOR (ENVOLVENDO AUTORIDADES)" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA NOTIFICÁ-LO SOBRE SUA INCLUSÃO NO SPVD DEVIDO AO REDS Nº *********, REGISTRADO EM SEU DESFAVOR POR SUA (EX-) COMPANHEIRA, *********, RG *********. " + "\n\n" + " ********* ASSINOU O TERMO DE NOTIFICAÇÃO DE INSERÇÃO NO SPVD E RECEBEU UMA CÓPIA DO REFERIDO TERMO. DEMAIS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES. "
}

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: RECUSA DA VÍTIMA (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: RECUSA DA VÍTIMA (ENVOLVENDO AUTORIDADES)" + "\n\n" + " APÓS VERIFICAR A EXISTÊNCIA DO REDS ********* NO QUAL *********, RG *********, FIGURA COMO VÍTIMA DE VIOLÊNCIA DOMÉSTICA PRATICADA PELO AUTOR *********, RG *********, A EQUIPE DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA COMPARECEU À RESIDÊNCIA DELA, PARA INCLUÍ-LA NO SERVIÇO DE PREVENÇÃO A VIOLÊNCIA DOMÉSTICA (SPVD)." + "\n\n" + " NO LOCAL, A EQUIPE APRESENTOU PARA A ASSISTIDA O SERVIÇO DA PMMG, CONTUDO ELA RECUSOU O ACOMPANHAMENTO. " + "\n\n" + " EMBORA A ASSISTIDA TENHA RECUSADO A INTERVENÇÃO DA PMMG, A EQUIPE APRESENTOU A ELA A LEI 11.340/06 - LEI MARIA DA PENHA, ESCLARECENDO-A SOBRE AS FORMAS DE VIOLÊNCIA DOMÉSTICA E O CICLO DESSA VIOLÊNCIA. ELA AINDA FOI ORIENTADA A ACIONAR A PMMG E/OU COMPARECER À DELEGACIA DE ATENDIMENTO À MULHER PARA SOLICITAR PROVIDÊNCIAS CABÍVEIS, CASO O ASSISTIDO PRATIQUE NOVO ATO DE VIOLÊNCIA, BEM COMO INFORMADA DA EXISTÊNCIA DOS OUTROS ÓRGÃOS DA REDE DE ENFRENTAMENTO À VIOLÊNCIA DOMÉSTICA CONTRA A MULHER QUE PODERÃO SER ACIONADOS, CONFORME O CASO EXIGIR." + "\n\n" + " ********* ASSINOU O TERMO DE RECUSA DE INCLUSÃO NO SPVD E RECEBEU UMA CÓPIA DO REFERIDO TERMO." + "\n\n" + " DEMAIS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AUTORIDADES AS COMPETENTES. " 
}

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: VÍTIMA NÃO LOCALIZADA") {
  document.getElementById("idteste").value = " NUMERO 01PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: VÍTIMA NÃO LOCALIZADA" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), PROCURAMOS POR *********, RG *********, PARA INCLUÍ-LA NO SERVIÇO DEVIDO AO REGISTRO DA OCORRÊNCIA Nº *********, EM DESFAVOR DE SEU (EX-) COMPANHEIRO, *********, RG *********. (CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), PROCURAMOS POR *********, RG *********, PARA MONITORAR O CASO ENVOLVENDO ELA E SEU (EX-) COMPANHEIRO, *********, RG *********, DEVIDO A REINCIDÊNCIA REGISTRADA NO BOLETIM Nº *********.) " + "\n\n" + " ESTA É A TERCEIRA TENTATIVA DE LOCALIZAÇÃO DA ASSISTIDA. AS DUAS PRIMEIRAS ESTÃO REGISTRADAS NOS BOS: ********* E *********. AINDA TENTAMOS CONTATO TELEFÔNICO ATRAVÉS DO NÚMERO *********, MAS A LIGAÇÃO FOI DIRECIONADA PARA A CAIXA POSTAL. " + "\n\n" + " INSTA OBSERVAR QUE A EQUIPE ACIONOU A SIRENE DA VIATURA, PARA QUE ********* PUDESSE PERCEBER A PRESENÇA POLICIAL NO LOCAL, UTILIZAMOS O INTERFONE, BEM COMO BATEMOS NO PORTÃO POR DIVERSAS VEZES, CONTUDO, NÃO FOMOS RECEBIDOS POR QUALQUER PESSOA. SALIENTA-SE QUE A EQUIPE PVD REALIZOU CONSULTA AO SISTEMA INTEGRADO DE DEFESA SOCIAL (SIDS), OBJETIVANDO LOCALIZAR OUTRO ENDEREÇO E/OU TELEFONE DE CONTATO DA ASSISTIDA OU DE FAMILIARES. ENTRETANTO, NÃO HÁ OUTRA OCORRÊNCIA EM DATA RECENTE, TAMPOUCO OUTRO CONTATO TELEFÔNICO. " + "\n\n" + " DIANTE DO EXPOSTO, NA IMPOSSIBILIDADE DE LOCALIZAR A ASSISTIDA, DAMOS POR ENCERRADO O MONITORAMENTO DO CASO. " + "\n\n" + " (NO LOCAL, REALIZAMOS CONTATO COM *********, RG *********, O QUAL É EX-VIZINHO DA ASSISTIDA, E FOMOS INFORMADOS QUE ********* SE MUDOU JUNTAMENTE COM SEU COMPANHEIRO, SENDO QUE A TESTEMUNHA NÃO SOUBE INFORMAR O NOVO ENDEREÇO OU TELEFONE DAS PARTES. TENTAMOS CONTATO TELEFÔNICO NO NÚMERO DISPONIBILIZADO NO REDS, *********, MAS A LIGAÇÃO FOI DIRECIONADA PARA A CAIXA POSTAL. SALIENTA-SE QUE A EQUIPE PVD REALIZOU CONSULTA AO SISTEMA INTEGRADO DE DEFESA SOCIAL (SIDS), OBJETIVANDO LOCALIZAR OUTRO ENDEREÇO E/OU TELEFONE DE CONTATO DA ASSISTIDA OU DE FAMILIARES. ENTRETANTO, NÃO HÁ OUTRA OCORRÊNCIA EM DATA RECENTE, TAMPOUCO OUTRO CONTATO TELEFÔNICO.)" + "\n" + " (NÃO OBTIVEMOS ÊXITO EM LOCALIZAR O ENDEREÇO CADASTRADO NO REDS, RUA *********. CHAMAMOS NOS INTERFONES DOS ENDEREÇOS NA RUA E O MORADOR EM FRENTE INFORMOU QUE NÃO CONHECIA OS ENVOLVIDOS ALEGANDO QUE RESIDE NO LOCAL HÁ ********* ANOS. NÃO LOCALIZAMOS OUTRO MEIO DE CONTATO COM A ASSISTIDA, UMA VEZ QUE PESQUISAMOS NO SISTEMA REDS E NENHUM TELEFONE OU REGISTRO FOI LOCALIZADO. DESSE MODO, DEVIDO A NÃO LOCALIZAÇÃO DOS ENVOLVIDOS, DAMOS POR ENCERRADO O MONITORAMENTO DO CASO. SALIENTA-SE QUE A EQUIPE PVD REALIZOU CONSULTA AO SISTEMA INTEGRADO DE DEFESA SOCIAL (SIDS), OBJETIVANDO LOCALIZAR OUTRO ENDEREÇO E/OU TELEFONE DE CONTATO DA ASSISTIDA OU DE FAMILIARES. ENTRETANTO, NÃO HÁ OUTRA OCORRÊNCIA EM DATA RECENTE, TAMPOUCO OUTRO CONTATO TELEFÔNICO.) "
}

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: AUTOR NÃO LOCALIZADO") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: AUTOR NÃO LOCALIZADO" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), PROCURAMOS POR *********, RG *********, PARA NOTIFICÁ-LO ACERCA DE SUA INCLUSÃO NO SERVIÇO DEVIDO AO REGISTRO DA OCORRÊNCIA Nº *********, EFETUADO EM SEU DESFAVOR PELA SUA (EX-) COMPANHEIRA, *********, RG *********. (CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), PROCURAMOS POR *********, RG *********, PARA DAR SEQUÊNCIA AO MONITORAMENTO DO CASO ENVOLVENDO ELE E SUA (EX-) COMPANHEIRA, *********, RG *********)." + "\n\n" + " EM DUAS DATAS ANTERIORES JÁ FORAM REALIZADAS TENTATIVAS INFRUTÍFERAS DE LOCALIZAÇÃO DO ASSISTIDO, CONFORME REGISTRADO NOS BOS: ********* E *********. " + "\n\n" + " SALIENTA-SE QUE A EQUIPE DO SPVD REALIZOU CONSULTA AO SISTEMA INTEGRADO DE DEFESA SOCIAL (SIDS), OBJETIVANDO LOCALIZAR OUTRO ENDEREÇO E/OU TELEFONE DE CONTATO DO ASSISTIDO. ENTRETANTO, NÃO HOUVE OUTRA OCORRÊNCIA EM DATA RECENTE, TAMPOUCO OUTRO CONTATO TELEFÔNICO." + "\n\n" + " ESTA É A TERCEIRA TENTATIVA DE LOCALIZAÇÃO DO ASSISTIDO PARA DAR SEQUÊNCIA AO PROTOCOLO DO SPVD. DESSE MODO, NÃO RETORNAREMOS AO LOCAL, A MENOS QUE SEJA REGISTRADO UM NOVO FATO OU A EQUIPE OBTENHA NOVA INFORMAÇÃO QUE POSSIBILITE A SUA LOCALIZAÇÃO. " + "\n\n" + " MESMO NA IMPOSSIBILIDADE DE LOCALIZAR O ASSISTIDO, CONTINUAREMOS O MONITORAMENTO DO CASO COM A ASSISTIDA."
}

if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: APRESENTAÇÃO DA LEI PARA A VÍTIMA (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: APRESENTAÇÃO DA LEI PARA A VÍTIMA (ENVOLVENDO AUTORIDADES)" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM A ASSISTIDA *********, RG *********, A QUAL ESTÁ SENDO ACOMPANHADA POR ESTA EQUIPE, DEVIDO A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********." + "\n\n" + " ESTA EQUIPE APRESENTOU PARA A ASSISTIDA OS PRINCIPAIS PONTOS DA LEI 11.340/06 - LEI MARIA DA PENHA, COM ÊNFASE NAS FORMAS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, FUNCIONAMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA E SOBRE A IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL. FOI DISCORRIDO TAMBÉM SOBRE AS SANÇÕES LEGAIS PREVISTAS NO CASO DO COMETIMENTO DE CRIMES CONTRA MULHERES, DENTRE ELAS A PREVISTA NO ART. 24-A DA REFERIDA LEI, A QUAL TIPIFICA O CRIME DE DESCUMPRIMENTO DE MEDIDAS PROTETIVAS DE URGÊNCIA IMPOSTAS EM RAZÃO DE VIOLÊNCIA DOMÉSTICA PRATICADA CONTRA MULHERES. " + "\n\n" + " DEMAIS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES AS COMPETENTES." + "\n\n" + " DAREMOS CONTINUIDADE AO PROTOCOLO DE ATENDIMENTO." 
}

//INICIO DOS NOVOS EDITADOS 12/02/2024
//
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: APRESENTAÇÃO DA LEI PARA O AUTOR (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: APRESENTAÇÃO DA LEI PARA O AUTOR (ENVOLVENDO AUTORIDADES)" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, O QUAL ESTÁ SENDO ACOMPANHADO POR ESTA EQUIPE, DEVIDO A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELE E SUA (EX-)COMPANHEIRA, *********, RG *********." + "\n\n" + " ESTA EQUIPE APRESENTOU PARA O ASSISTIDO OS PRINCIPAIS PONTOS DA LEI 11.340/06 - LEI MARIA DA PENHA, COM ÊNFASE NAS FORMAS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, FUNCIONAMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA E SOBRE A IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL. FOI DISCORRIDO TAMBÉM SOBRE AS SANÇÕES LEGAIS PREVISTAS NO CASO DO COMETIMENTO DE CRIMES CONTRA MULHERES, DENTRE ELAS A PREVISTA NO ART. 24-A DA REFERIDA LEI, A QUAL TIPIFICA O CRIME DE DESCUMPRIMENTO DE MEDIDAS PROTETIVAS DE URGÊNCIA IMPOSTAS EM RAZÃO DE VIOLÊNCIA DOMÉSTICA PRATICADA CONTRA MULHERES." + "\n\n" + " DEMAIS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES. " + "\n\n" + " DAREMOS CONTINUIDADE AO PROTOCOLO DE ATENDIMENTO." 
}
//CONFERE
//
///
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: CONTATO COM TESTEMUNHAS (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: CONTATO COM TESTEMUNHAS (ENVOLVENDO AUTORIDADES)" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM A TESTEMUNHA *********, DEVIDO AO MONITORAMENTO DO CASO DE VIOLÊNCIA DOMÉSTICA ENVOLVENDO A ASSISTIDA, *********, RG *********, E O ASSISTIDO, *********, RG *********." + "\n\n" + " AS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES." + "\n\n" + " DAREMOS CONTINUIDADE AO PROTOCOLO DE ATENDIMENTO." 
}


//CONFERE
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ENCAMINHAMENTO (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ENCAMINHAMENTO (ENVOLVENDO AUTORIDADES)" + "\n\n" + " DURANTE VISITA (DE INCLUSÃO DA VÍTIMA NO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD)/ DE MONITORAMENTO DA VÍTIMA/ DE APRESENTAÇÃO DA LEI PARA A VÍTIMA/ DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REFERENTE AO CASO DE VIOLÊNCIA DOMÉSTICA ENVOLVENDO *********, RG *********, E *********, RG *********, FOI OBSERVADA A NECESSIDADE DE ENCAMINHAR A ASSISTIDA PARA OS ÓRGÃOS DA REDE DE ATENDIMENTO À MULHER EM SITUAÇÃO DE VIOLÊNCIA EM BELO HORIZONTE. ********* CONCORDOU COM O ENCAMINHAMENTO E ENTRARÁ EM CONTATO PARA VERIFICAR AS CONDIÇÕES DE ATENDIMENTO. " + "\n\n" + " A ASSISTIDA ASSINOU O TERMO DE ENCAMINHAMENTO." + "\n\n" + " DAREMOS SEQUÊNCIA AO MONITORAMENTO. (O CASO NÃO SERÁ MONITORADO, POIS ********* RECUSOU SUA INCLUSÃO NO SPVD.)"
}


//CONFERE
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DA VÍTIMA (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DA VÍTIMA (ENVOLVENDO AUTORIDADES)" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA MONITORAR A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. " + "\n\n" + " NA OCASIÃO, REFORÇAMOS COM A ASSISTIDA SOBRE TODAS AS INFORMAÇÕES REPASSADAS ANTERIORMENTE, TAIS COMO: PROVIDÊNCIAS A SEREM ADOTADAS DIANTE DE NOVOS EPISÓDIOS DE VIOLÊNCIA, LEGISLAÇÕES QUE VERSAM SOBRE OS DIREITOS DAS MULHERES, O FUNCIONAMENTO DE UMA MEDIDA PROTETIVA, ÓRGÃOS QUE ATUAM NA PREVENÇÃO A VIOLÊNCIA DOMÉSTICA, DENTRE OUTROS. DEMAIS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES. DAREMOS CONTINUIDADE AO MONITORAMENTO DO CASO." 
}

//CONFERE 
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DA VÍTIMA EM VIRTUDE DE REINCIDÊNCIA APÓS O ENCERRAMENTO DO CASO") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DA VÍTIMA EM VIRTUDE DE REINCIDÊNCIA APÓS O ENCERRAMENTO DO CASO" + "\n\n" + " NA PRESENTE DATA, CUMPRINDO PROTOCOLO DE ATENDIMENTO DE SEGUNDA RESPOSTA DO SPVD, DESLOCAMO-NOS AO ENDEREÇO CADASTRADO EM CAMPO ESPECÍFICO, SENDO A EQUIPE RECEBIDA POR *********, RG *********, A QUAL NOS RELATOU QUE, DESDE O ENCERRAMENTO DO ACOMPANHAMENTO REALIZADO PELA EQUIPE DO SPVD, ELA VOLTOU A TER PROBLEMAS COM O (EX-)COMPANHEIRO, *********, RG *********, O QUAL FIGURA NOVAMENTE COMO AUTOR DE VIOLÊNCIA DOMÉSTICA NO REDS N° *********." + "\n\n" + " RESSALTA-SE QUE A ASSISTIDA E O ASSISTIDO FORAM MONITORADOS POR UMA EQUIPE DE SEGUNDA RESPOSTA DO SPVD, MAIS PRECISAMENTE NO LAPSO ENTRE ********* E *********, OPORTUNIDADE NA QUAL O PROTOCOLO FORA ENCERRADO E A SITUAÇÃO SE PACIFICARA." + "\n\n" + " SALIENTA-SE QUE, VIGE CONTRA ********* MEDIDAS PROTETIVAS DE URGÊNCIA PREVISTAS NA LEI Nº. 11.340/06 – LEI MARIA DA PENHA, CONFORME OS AUTOS DO PROCESSO N° *********, EXPEDIDAS PELO JUÍZO DO *********º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER." + "\n\n" + " A ASSISTIDA RELATOU QUE TEME POR SUA SEGURANÇA, HAJA VISTA, TODO O HISTÓRICO PREGRESSO ENTRE ELA E O ASSISTIDO, E QUE, CONSTANTEMENTE, O ASSISTIDO COMPARECE A PORTA DA RESIDÊNCIA DELA PARA BUSCAR A FILHA, MESMO COM A MEDIDA PROTETIVA FIXANDO O AFASTAMENTO DO LAR, DOMICÍLIO OU LOCAL DE CONVIVÊNCIA, QUE O ASSISTIDO INSISTE EM PRATICAR O DELITO DE DESCUMPRIMENTO DE MEDIDA PROTETIVA DE URGÊNCIA DE FORMA DELIBERADA E REITERADA." + "\n\n" + " RESSALTA-SE QUE O CASAL ESTÁ COM ALTO ÍNDICE DE REPETIÇÕES DE EPISÓDIOS DE VIOLÊNCIA DOMÉSTICA; EM CONSULTA AO SISTEMA REDS, FORAM LOCALIZADOS ********* (*********) BOLETINS DE OCORRÊNCIAS ENVOLVENDO AS PARTES." + "\n\n" + " A EQUIPE DO SPVD REITEROU SOBRE AS ESTRATÉGIAS DE PROTEÇÃO, A QUEM ACIONAR NO CASO DE DESCUMPRIMENTO DA MEDIDA PROTETIVA DE URGÊNCIA, BEM COMO SEMPRE ESTAR DE POSSE DE UMA CÓPIA DA ORDEM JUDICIAL. TAMBÉM REFORÇAMOS ACERCA DAS LEGISLAÇÕES QUE VERSAM SOBRE OS DIREITOS DAS MULHERES, ÓRGÃOS QUE ATUAM NA PREVENÇÃO A VIOLÊNCIA DOMÉSTICA, A QUEBRA DO CICLO DA VIOLÊNCIA, DENTRE OUTROS." + "\n\n" + " A EQUIPE IRÁ ARTICULAR ESTRATÉGIAS JUNTO À REDE DE PROTEÇÃO À MULHER OBJETIVANDO ATIVAR MAIORES MECANISMOS DE SEGURANÇA E PRESERVAÇÃO DE SEUS DIREITOS." + "\n\n" + " DIANTE DO EXPOSTO, A EQUIPE CONFECCIONARÁ RELATÓRIO A SER REMETIDO AO PODER JUDICIÁRIO E AO MINISTÉRIO PÚBLICO, RESSALTANDO A NECESSIDADE SE ROMPER O CICLO DE VIOLÊNCIA EM QUE AS PARTES ESTÃO INSERIDAS." + "\n\n" + " POR TRATAR-SE DE UM CASO DE REINCIDÊNCIA, O PROTOCOLO NÃO SERÁ APLICADO NOVAMENTE, CONTUDO, TODAS AS MEDIDAS COMPLEMENTARES POSSÍVEIS SERÃO TOMADAS. "
}
//CONFERE 
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DA VÍTIMA EM VIRTUDE DE REINCIDÊNCIA APÓS O ENCERRAMENTO DO CASO (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DA VÍTIMA EM VIRTUDE DE REINCIDÊNCIA APÓS O ENCERRAMENTO DO CASO (ENVOLVENDO AUTORIDADES)" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, EM VIRTUDE DE REINCIDÊNCIA DE VIOLÊNCIA DOMÉSTICA APÓS O ENCERRAMENTO DO CASO, EM QUE FIGURA COMO AUTOR O SEU (EX-)COMPANHEIRO, *********, RG *********. " + "\n\n" + " NA OCASIÃO, REFORÇAMOS COM A ASSISTIDA AS INFORMAÇÕES REPASSADAS ANTERIORMENTE, TAIS COMO: PROVIDÊNCIAS A SEREM ADOTADAS DIANTE DE NOVOS EPISÓDIOS DE VIOLÊNCIA, LEGISLAÇÕES QUE VERSAM SOBRE OS DIREITOS DAS MULHERES, FUNCIONAMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA, ÓRGÃOS QUE ATUAM NA PREVENÇÃO A VIOLÊNCIA DOMÉSTICA, DENTRE OUTRAS. A EQUIPE DO SPVD REITEROU SOBRE AS ESTRATÉGIAS DE PROTEÇÃO, A QUEM ACIONAR NO CASO DE DESCUMPRIMENTO DA MEDIDA PROTETIVA DE URGÊNCIA, BEM COMO SEMPRE ESTAR DE POSSE DE UMA CÓPIA DA ORDEM JUDICIAL. " + "\n\n" + " MAIORES INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES."
}

//confere
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DO AUTOR (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DO AUTOR (ENVOLVENDO AUTORIDADES)" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, O QUAL ESTÁ SENDO ACOMPANHADO POR ESTA EQUIPE, DEVIDO A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELE E SUA (EX-)COMPANHEIRA, *********, RG *********." + "\n\n" + " INFORMAÇÕES IMPORTANTES REPASSADAS ANTERIORMENTE FORAM REFORÇADAS COM O ASSISTIDO, TAIS COMO: FORMAS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, FUNCIONAMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA, A IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL E SANÇÕES LEGAIS PREVISTAS NO CASO DO COMETIMENTO DE CRIMES CONTRA MULHERES." + "\n\n" + " DEMAIS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES." + "\n\n" + " DAREMOS CONTINUIDADE AO MONITORAMENTO DO CASO. " 
}

//CONFERE
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DO AUTOR EM VIRTUDE DE REINCIDÊNCIA APÓS O ENCERRAMENTO DO CASO") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DO AUTOR EM VIRTUDE DE REINCIDÊNCIA APÓS O ENCERRAMENTO DO CASO" + "\n\n" + " NA PRESENTE DATA, CUMPRINDO PROTOCOLO DE ATENDIMENTO DE SEGUNDA RESPOSTA DO SPVD, DESLOCAMO-NOS AO ENDEREÇO CADASTRADO EM CAMPO ESPECÍFICO, SENDO A EQUIPE RECEBIDA POR *********, RG *********, O QUAL NOS RELATOU QUE, DESDE O ENCERRAMENTO DO ACOMPANHAMENTO REALIZADO PELA EQUIPE DO SPVD, ELE VOLTOU A TER PROBLEMAS COM SUA (EX-)COMPANHEIRA, *********, RG *********, CONFORME REDS DE N° *********. " + "\n\n" + " RESSALTA-SE QUE A ASSISTIDA E O ASSISTIDO FORAM MONITORADOS POR UMA EQUIPE DE SEGUNDA RESPOSTA DO SPVD, MAIS PRECISAMENTE NO LAPSO ENTRE ********* E *********, OPORTUNIDADE NA QUAL O PROTOCOLO FORA ENCERRADO E SITUAÇÃO SE PACIFICARA. " + "\n\n" + " SALIENTA-SE QUE VIGE CONTRA O ASSISTIDO MEDIDAS PROTETIVAS DE URGÊNCIA PREVISTAS NA LEI Nº. 11.340/06 – LEI MARIA DA PENHA, CONFORME PROCESSO N° *********, EXPEDIDAS PELO JUÍZO DO *********º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER. O ASSISTIDO RELATOU QUE *********." + "\n\n" + " RESSALTA-SE QUE O CASAL ESTÁ COM ALTO ÍNDICE DE REPETIÇÕES DE EPISÓDIOS DE VIOLÊNCIA DOMÉSTICA; EM CONSULTA AO SISTEMA REDS, FORAM LOCALIZADOS ********* (*********) BOLETINS DE OCORRÊNCIAS ENVOLVENDO AS PARTES." + "\n\n" + " A EQUIPE PPVD REITEROU SOBRE AS ESTRATÉGIAS DE PROTEÇÃO, FORMAS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, FUNCIONAMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA, A IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL E SANÇÕES LEGAIS PREVISTAS NO CASO DO COMETIMENTO DE CRIMES CONTRA MULHERES." + "\n\n" + " A EQUIPE IRÁ ARTICULAR ESTRATÉGIAS JUNTO À REDE DE PROTEÇÃO À MULHER OBJETIVANDO ATIVAR MAIORES MECANISMOS DE SEGURANÇA E PRESERVAÇÃO DE DIREITOS.  " + "\n\n" + " POR TRATAR-SE DE UM CASO DE REINCIDÊNCIA, O PROTOCOLO NÃO SERÁ APLICADO NOVAMENTE, CONTUDO TODAS AS MEDIDAS COMPLEMENTARES POSSÍVEIS SERÃO TOMADAS."
}

//CONFERE
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DO AUTOR EM VIRTUDE DE REINCIDÊNCIA APÓS O ENCERRAMENTO DO CASO (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: MONITORAMENTO DO AUTOR EM VIRTUDE DE REINCIDÊNCIA APÓS O ENCERRAMENTO DO CASO (ENVOLVENDO AUTORIDADES)" + "\n\n" + " CONFORME PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, EM VIRTUDE DE REINCIDÊNCIA DE VIOLÊNCIA DOMÉSTICA APÓS O ENCERRAMENTO DO CASO, EM QUE FIGURA COMO VÍTIMA A SUA (EX-)COMPANHEIRA, *********, RG *********. " + "\n\n" + " NA OCASIÃO, REFORÇAMOS COM O ASSISTIDO AS INFORMAÇÕES REPASSADAS ANTERIORMENTE, TAIS COMO: FORMAS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, FUNCIONAMENTO DAS MEDIDAS PROTETIVAS DE URGÊNCIA, A IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL E SANÇÕES LEGAIS PREVISTAS NO CASO DO COMETIMENTO DE CRIMES CONTRA MULHERES." + "\n\n" + " AS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES." 
}


//CONFERE
///
/////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO POR SOLICITAÇÃO DA VÍTIMA (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO POR SOLICITAÇÃO DA VÍTIMA (ENVOLVENDO AUTORIDADES)" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA MONITORAR A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. " + "\n\n" + " DURANTE O CONTATO, A ASSISTIDA SOLICITOU O DESLIGAMENTO DO SPVD, ASSINOU O TERMO DE DESLIGAMENTO POR SOLICITAÇÃO E RECEBEU UMA CÓPIA DO REFERIDO TERMO. NA OCASIÃO, REFORÇAMOS AS ORIENTAÇÕES COM ********* ACERCA DOS PROCEDIMENTOS A SEREM ADOTADOS DIANTE DE NOVOS EPISÓDIOS DE VIOLÊNCIA, SOBRE O FUNCIONAMENTO DE UMA MEDIDA PROTETIVA, SOBRE OS DISPOSITIVOS LEGAIS QUE VERSAM SOBRE OS DIREITOS DAS MULHERES E DA IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL. " + "\n\n" + " DIANTE DA SOLICITAÇÃO DA ASSISTIDA, ELA ESTÁ SENDO DESLIGADA DO SERVIÇO E DAMOS POR ENCERRADO O MONITORAMENTO DO CASO. " + "\n\n" + " DEMAIS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES. "
}

//CONFERE
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ENCERRAMENTO DO CASO (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: ENCERRAMENTO DO CASO (ENVOLVENDO AUTORIDADES)" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA FINALIZAR O ACOMPANHAMENTO DO CASO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. " + "\n\n" + " REFORÇAMOS COM A ASSISTIDA AS INFORMAÇÕES IMPORTANTES ANTERIORMENTE REPASSADAS, TAIS COMO: PROVIDÊNCIAS A SEREM ADOTADAS DIANTE DE NOVOS EPISÓDIOS DE VIOLÊNCIA, LEGISLAÇÕES QUE VERSAM SOBRE OS DIREITOS DAS MULHERES, O FUNCIONAMENTO DE UMA MEDIDA PROTETIVA, PRINCIPAIS ÓRGÃOS QUE ATUAM NA PREVENÇÃO A VIOLÊNCIA DOMÉSTICA E A ATRIBUIÇÃO DE CADA UM. " + "\n\n" + " DEMAIS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES. " + "\n\n" + " DIANTE DO CUMPRIMENTO DO PROTOCOLO DE SEGUNDA RESPOSTA DO SPVD, ESTA EQUIPE ENCERRA O ACOMPANHAMENTO DO CASO. "
}


//CONFERE 
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: SUSPENSÃO DO CASO") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: SUSPENSÃO DO CASO" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA MONITORAR A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. " + "\n\n" + " A ASSISTIDA FOI INCLUÍDA NO ACOMPANHAMENTO DO SERVIÇO EM *********, PORÉM CONSTATAMOS QUE ********* SE ENCONTRA PRESO DESDE O DIA *********, NO PRESÍDIO *********, DEVIDO A *********. " + "\n\n" + " QUESTIONADA, A ASSISTIDA RELATOU QUE NÃO TEVE MAIS NENHUM TIPO DE CONTATO COM ELE, NEM ATRAVÉS DE TERCEIROS, BEM COMO DISSE QUE ESTÁ SE SENTINDO MAIS SEGURA E, ATUALMENTE, ESTÁ CONSEGUINDO TRABALHAR MAIS TRANQUILA.  " + "\n\n" + " REFORÇAMOS COM A ASSISTIDA IMPORTANTES INFORMAÇÕES, TAIS COMO: PROVIDÊNCIAS A SEREM ADOTADAS DIANTE DE NOVOS EPISÓDIOS DE VIOLÊNCIA, LEGISLAÇÕES QUE VERSAM SOBRE OS DIREITOS DAS MULHERES, O FUNCIONAMENTO DE UMA MEDIDA PROTETIVA, PRINCIPAIS ÓRGÃOS QUE ATUAM NA PREVENÇÃO A VIOLÊNCIA DOMÉSTICA E A ATRIBUIÇÃO DE CADA UM. " + "\n\n" + " A ASSISTIDA FOI COMUNICADA QUE AS VISITAS PRESENCIAIS DA EQUIPE SERÃO SUSPENSAS ATÉ A LIBERAÇÃO DO ASSISTIDO E QUE, TÃO LOGO TOME CONHECIMENTO DA SOLTURA DESTE, ENTRE EM CONTATO COM A GUARNIÇÃO ATRAVÉS DOS CONTATOS DISPONIBILIZADOS PARA QUE SEJA RETOMADO O ACOMPANHAMENTO. DE IGUAL MANEIRA, FOI INFORMADA PARA QUE, CASO O ASSISTIDO, MESMO RECLUSO NO SISTEMA PRISIONAL, COMETA UM NOVO ATO DE VIOLÊNCIA CONTRA ELA, FAÇA O DEVIDO REGISTRO DO FATO, ENTRE EM CONTATO COM ESTA EQUIPE E BUSQUE O AUXÍLIO DOS DEMAIS ÓRGÃOS DA REDE, CASO NECESSÁRIO. " + "\n\n" + " DIANTE DO EXPOSTO, O CASO SERÁ SUSPENSO ATÉ A SOLTURA DO ASSISTIDO OU REGISTRO DE UM NOVO EPISÓDIO DE VIOLÊNCIA, CONTUDO SEM PREJUÍZO PARA O MONITORAMENTO A DISTÂNCIA VIA CONSULTA DO SISTEMA INTEGRADO DE DEFESA SOCIAL (SIDS). " 
}

//CONFERE
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO PELA EQUIPE") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO PELA EQUIPE" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA MONITORAR A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. " + "\n\n" + " A REFERIDA RELATOU QUE, MESMO COM A EXISTÊNCIA DAS MEDIDAS PROTETIVAS, PROCESSO Nº *********, REFERENTE AO *********º JUIZADO DE VIOLÊNCIA DOMÉSTICA, AS PARTES CONTATAM-SE PARA CONVERSAR E O ÚLTIMO DIÁLOGO OCORREU NA DATA DE *********. " + "\n\n" + " EM VISITAS ANTERIORES, TANTO EM CONTATO COM A TESTEMUNHA ********* QUANTO COM A PROPRIETÁRIA DO IMÓVEL, FOMOS INFORMADOS QUE AS PARTES ESTAVAM JUNTAS. " + "\n\n" + " MESMO APÓS AS EXAUSTIVAS ORIENTAÇÕES À ASSISTIDA ACERCA DO FUNCIONAMENTO DAS MEDIDAS PROTETIVAS, ESTA NÃO AGE DE ACORDO COM AS INFORMAÇÕES REPASSADAS E CONTINUA MANTENDO CONTATO COM O ASSISTIDO." + "\n\n" + " ENFATIZA-SE QUE O CASAL POSSUI AO TODO ********* REGISTROS ENTRE *********, OS QUAIS RELATAM O CRIME DE VIOLÊNCIA CONTRA A MULHER. FORAM CUMPRIDOS OS SEGUINTES PASSOS DO PROTOCOLO DO SPVD COM AS PARTES: *********. " + "\n\n" + " DIANTE DO EXPOSTO, REFORÇAMOS AS ORIENTAÇÕES COM ********* ACERCA DOS PROCEDIMENTOS A SEREM ADOTADOS DIANTE DE NOVOS EPISÓDIOS DE VIOLÊNCIA, SOBRE O FUNCIONAMENTO DAS MEDIDAS PROTETIVAS, OS DISPOSITIVOS LEGAIS QUE VERSAM SOBRE OS DIREITOS DAS MULHERES E A IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL." + "\n\n" + "O CASO ESTÁ SENDO ENCERRADO DEVIDO ********* NÃO SEGUIR AS ORIENTAÇÕES REPASSADAS POR ESTA EQUIPE. A ASSISTIDA ESTÁ CIENTE E ASSINOU O TERMO DE DESLIGAMENTO. "
}

//CONFERE 
/// 
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO PELA EQUIPE (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO PELA EQUIPE (ENVOLVENDO AUTORIDADES)" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA MONITORAR A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. " + "\n\n" + " AS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES." + "\n\n" + " NA OCASIÃO, REFORÇAMOS COM A ASSISTIDA IMPORTANTES INFORMAÇÕES, TAIS COMO: PROVIDÊNCIAS A SEREM ADOTADAS DIANTE DE NOVOS EPISÓDIOS DE VIOLÊNCIA, LEGISLAÇÕES QUE VERSAM SOBRE OS DIREITOS DAS MULHERES, O FUNCIONAMENTO DE UMA MEDIDA PROTETIVA, PRINCIPAIS ÓRGÃOS QUE ATUAM NA PREVENÇÃO A VIOLÊNCIA DOMÉSTICA E A ATRIBUIÇÃO DE CADA UM. " + "\n\n" + " ********* ASSINOU O TERMO DE DESLIGAMENTO DA ASSISTIDA DO SPVD E RECEBEU UMA CÓPIA DO REFERIDO TERMO. " + "\n\n" + " DIANTE DO EXPOSTO, A ASSISTIDA ESTÁ SENDO DESLIGADA DO SPVD POR ESTA EQUIPE E O CASO NÃO SERÁ MAIS ACOMPANHADO, A NÃO SER QUE HAJA O REGISTRO DE UM NOVO FATO." 
}

//CONFERE
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO POR SOLICITAÇÃO DA VÍTIMA") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO POR SOLICITAÇÃO DA VÍTIMA" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REALIZAMOS CONTATO COM *********, RG *********, PARA MONITORAR A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. " + "\n\n" + " A ASSISTIDA RELATOU QUE NÃO TEM INTERESSE EM SOLICITAR MEDIDAS PROTETIVAS DE URGÊNCIA, QUE O ASSISTIDO CONTINUA MORANDO NA CASA COM ELA E QUE DESEJA MANTER O RELACIONAMENTO. DISSE AINDA QUE, EM RELAÇÃO AO ACOMPANHAMENTO DO SPVD, DESEJA QUE AS VISITAS PAREM DE ACONTECER. " + "\n\n" + " DESSE MODO, ********* INFORMOU QUE NÃO HÁ NECESSIDADE DESTA EQUIPE DAR CONTINUIDADE AO MONITORAMENTO, TENDO EM VISTA TAMBÉM NÃO TER OCORRIDO NENHUM NOVO EPISÓDIO DE VIOLÊNCIA ENTRE AS PARTES." + "\n\n" + " ********* ASSINOU O TERMO DE DESLIGAMENTO DO SPVD POR SOLICITAÇÃO E RECEBEU UMA CÓPIA DO REFERIDO TERMO. " + "\n\n" + " NA OCASIÃO, REFORÇAMOS AS ORIENTAÇÕES COM A ASSISTIDA ACERCA DOS PROCEDIMENTOS A SEREM ADOTADOS DIANTE DE NOVOS EPISÓDIOS DE VIOLÊNCIA, SOBRE O FUNCIONAMENTO DE UMA MEDIDA PROTETIVA, SOBRE OS DISPOSITIVOS LEGAIS QUE VERSAM SOBRE OS DIREITOS DAS MULHERES E DA IMPORTÂNCIA DA QUEBRA DO CICLO DA VIOLÊNCIA NO ÂMBITO CONJUGAL." + "\n\n" + " DIANTE DA SOLICITAÇÃO DA ASSISTIDA, ELA ESTÁ SENDO DESLIGADA DO SERVIÇO E DAMOS POR ENCERRADO O MONITORAMENTO DO CASO. "
}

//CONFERE
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO POR NÃO LOCALIZAÇÃO DA VÍTIMA") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO POR NÃO LOCALIZAÇÃO DA VÍTIMA" + "\n\n" + " EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), PROCURAMOS POR *********, RG *********, PARA MONITORAR A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. " + "\n\n" + " RESSALTA-SE QUE ESTA É A TERCEIRA TENTATIVA SEGUIDA DE LOCALIZAÇÃO DA ASSISTIDA PARA DAR PROSSEGUIMENTO AO PROTOCOLO DE ATENDIMENTO, SENDO QUE AS TENTATIVAS ANTERIORES ESTÃO REGISTRADAS NOS BOLETINS: ********* E *********. A EQUIPE ACIONOU A SIRENE DA VIATURA POLICIAL, PARA QUE ********* PUDESSE PERCEBER A PRESENÇA POLICIAL NO LOCAL, TAMBÉM UTILIZAMOS O INTERFONE, BEM COMO BATEMOS NO PORTÃO POR DIVERSAS VEZES, CONTUDO, NÃO FOMOS RECEBIDOS QUALQUER PESSOA. " + "\n\n" + " EM TODAS AS OPORTUNIDADES TENTAMOS CONTATO TELEFÔNICO ATRAVÉS DO NÚMERO FORNECIDO PELA ASSISTIDA, *********, TODAVIA A LIGAÇÃO FOI DIRECIONADA PARA A CAIXA POSTAL. " + "\n\n" + " SALIENTA-SE QUE A EQUIPE REALIZOU CONSULTA AO SISTEMA INTEGRADO DE DEFESA SOCIAL (SIDS), OBJETIVANDO LOCALIZAR OUTRO ENDEREÇO E/OU TELEFONE DE CONTATO DA ASSISTIDA. ENTRETANTO, NÃO HÁ OUTRA OCORRÊNCIA EM DATA RECENTE, TAMPOUCO OUTRO CONTATO TELEFÔNICO. " + "\n\n" + " DIANTE DO EXPOSTO, REALIZAMOS O DESLIGAMENTO EM FACE DA IMPOSSIBILIDADE DE LOCALIZAÇÃO DA ASSISTIDA E O CASO NÃO SERÁ MAIS ACOMPANHADO, A NÃO SER QUE HAJA O REGISTRO DE UM NOVO FATO. " 
}

//CONFERE
///
////
if ( nome=="PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO POR NÃO LOCALIZAÇÃO DA VÍTIMA (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " PASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: DESLIGAMENTO POR NÃO LOCALIZAÇÃO DA VÍTIMA (ENVOLVENDO AUTORIDADES)" + "\n\n"+" EM CONTINUIDADE AO PROTOCOLO DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), PROCURAMOS POR *********, RG *********, PARA MONITORAR A SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA ENTRE ELA E SEU (EX-)COMPANHEIRO, *********, RG *********. " + "\n\n" + " RESSALTA-SE QUE ESTA É A TERCEIRA TENTATIVA SEGUIDA DE LOCALIZAÇÃO DA ASSISTIDA PARA DAR PROSSEGUIMENTO AO PROTOCOLO DE ATENDIMENTO, SENDO QUE AS TENTATIVAS ANTERIORES ESTÃO REGISTRADAS NOS BOLETINS: ********* E *********. " + "\n\n" + " DIANTE DO EXPOSTO, REALIZAMOS O DESLIGAMENTO EM FACE DA IMPOSSIBILIDADE DE LOCALIZAÇÃO DA ASSISTIDA E O CASO NÃO SERÁ MAIS ACOMPANHADO, A NÃO SER QUE HAJA O REGISTRO DE UM NOVO FATO.  " + "\n\n" + " DEMAIS INFORMAÇÕES COLETADAS SUBSIDIARÃO RELATÓRIO CIRCUNSTANCIADO DO CASO, QUE SERÁ ENCAMINHADO, POSTERIORMENTE, PARA AS AUTORIDADES COMPETENTES. " 
}

//CONFERE 
///
////
if ( nome=="ASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: RECUSA DE ENCAMINHAMENTO (ENVOLVENDO AUTORIDADES)") {
  document.getElementById("idteste").value = " ASSO DO PROTOCOLO DE 2ª RESPOSTA DO SPVD: RECUSA DE ENCAMINHAMENTO (ENVOLVENDO AUTORIDADES)" + "\n\n" + " DURANTE VISITA (DE INCLUSÃO DA VÍTIMA NO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD)/ DE MONITORAMENTO DA VÍTIMA/ DE APRESENTAÇÃO DA LEI PARA A VÍTIMA/ DO SERVIÇO DE PREVENÇÃO À VIOLÊNCIA DOMÉSTICA (SPVD), REFERENTE AO CASO DE VIOLÊNCIA DOMÉSTICA ENVOLVENDO *********, RG *********, E *********, RG *********, FOI OBSERVADA A NECESSIDADE DE ENCAMINHAR A ASSISTIDA PARA ABRIGAMENTO, CONTUDO, ********* RECUSOU O ENCAMINHAMENTO. " + "\n\n" + " A ASSISTIDA ASSINOU O TERMO DE RECUSA DE ENCAMINHAMENTO. " + "\n\n" + " DAREMOS SEQUÊNCIA AO MONITORAMENTO. (O CASO NÃO SERÁ MONITORADO, POIS ********* RECUSOU SUA INCLUSÃO NO SPVD.) "
}

//CONFERE 
///
////
if ( nome=="CONVITE PARA PARTICIPAÇÃO EM GRUPO REFLEXIVO") {
  document.getElementById("idteste").value = " CONVITE PARA PARTICIPAÇÃO EM GRUPO REFLEXIVO" + "\n\n" + " DURANTE O ACOMPANHAMENTO DO CASO DE VIOLÊNCIA DOMÉSTICA REFERENTE A ********* E *********, RG *********, CONVIDAMOS O ASSISTIDO PARA COMPARECIMENTO NÃO OBRIGATÓRIO AO GRUPO REFLEXIVO SOBRE GÊNERO PROMOVIDO PELO INSTITUTO CASA DA PALAVRA EM CONJUNTO COM A 1ª CIA PM IND PVD. O ENVOLVIDO FOI INFORMADO ACERCA DO PRÓXIMO ENCONTRO QUE OCORRERÁ NO DIA **/**/**** E QUE OS ENCONTROS OCORREM DE FORMA QUINZENAL. "
}

ocultarCarregamento()


}

// em outro arquivo

//


document.addEventListener("DOMContentLoaded", function() {
  const visualizarImpressaoLink = document.getElementById("visualizarImpressaoLink");

  if (visualizarImpressaoLink) {
    visualizarImpressaoLink.addEventListener("click", function(event) {
      // Previne o comportamento padrão do link para que possamos salvar os dados primeiro
      event.preventDefault();

      // Coleta todos os dados dos formulários
      const dadosFormulario = {};

      // Coleta dados dos inputs de texto, number, tel, date
      document.querySelectorAll('input[type="text"], input[type="number"], input[type="tel"], input[type="date"]').forEach(input => {
        dadosFormulario[input.id] = input.value;
      });

      // Coleta dados dos selects
      document.querySelectorAll('select').forEach(select => {
        dadosFormulario[select.id] = select.value;
      });

      // Coleta dados dos checkboxes (se houver na dadosVitima.html que precisem ser passados)
      // Para este projeto, parece que os checkboxes estão apenas em avRisco.html, mas é bom ter a lógica
      document.querySelectorAll('input[type="checkbox"]').forEach(checkbox => {
        dadosFormulario[checkbox.id] = checkbox.checked;
      });

      // Salva os dados no localStorage
      localStorage.setItem('dadosFormularioPVD', JSON.stringify(dadosFormulario));

      // Abre a nova aba
      window.open(visualizarImpressaoLink.href, '_blank');
    });
  }
});


// Obtém o link salvo
const linkSalvo = localStorage.getItem("linkAtual");

// Define como href do link, se existir
if (linkSalvo) {
  const link = document.querySelector('.aImagem');
  link.setAttribute('href', linkSalvo);
}

// Define como href do link, se existir
if (linkSalvo) {
  const link = document.querySelector('.editarVoltar');
  link.setAttribute('href', linkSalvo);
}


//relacaoVitimaAutor
//rgVitima   agressoesFisicas
////rgAgressor mpu violenciasPsicologicas
//FUNCAO QUE ALTERA O TEXTO temFilhos quantidadeFilhos nomesIdadesFilhos
function atualizardados2() {

  let CAMPO01 = document.getElementById("01");
  let CAMPO02 = document.getElementById("02");
  let CAMPO03 = document.getElementById("03");
  let CAMPO04 = document.getElementById("04");
  let CAMPO05 = document.getElementById("05");
  let CAMPO06 = document.getElementById("06");
  let CAMPO07 = document.getElementById("07");
  let CAMPO08 = document.getElementById("08");
  let CAMPO09 = document.getElementById("09");
  let CAMPO10 = document.getElementById("10");
  let CAMPO11 = document.getElementById("11");
  let CAMPO12 = document.getElementById("12");
  let CAMPO13 = document.getElementById("13");
  let CAMPO14 = document.getElementById("14");
  let CAMPO15 = document.getElementById("15");
  let CAMPO16 = document.getElementById("16");
  let CAMPO17 = document.getElementById("17");

   const relacaoVitimaAutor = localStorage.getItem("relacaoVitimaAutor");
   const separados = localStorage.getItem("separados");
   const tempoRelacionamento = localStorage.getItem("tempoRelacionamento");
   const tempoSeparacao = localStorage.getItem("tempoSeparacao");
   const temFilhos = localStorage.getItem("temFilhos");
   const quantidadeFilhos = localStorage.getItem("quantidadeFilhos");
   const nomesIdadesFilhos = localStorage.getItem("nomesIdadesFilhos");
   const mpu = localStorage.getItem("mpu");
   const acessoArma = localStorage.getItem("acessoArma");
   const violenciasPsicologicas = localStorage.getItem("violenciasPsicologicas");
   const agressoesFisicas = localStorage.getItem("agressoesFisicas");
   const agressoesMorais  = localStorage.getItem("agressoesMorais");
   const agressoesPatrimoniais  = localStorage.getItem("agressoesPatrimoniais");
   const agressoesSexuais = localStorage.getItem("agressoesSexuais");
   const filhosPresenciaramViolencia  = localStorage.getItem("filhosPresenciaramViolencia");
   const suicidioAgressor  = localStorage.getItem("suicidioAgressor");
   const usoSubstancias = localStorage.getItem("usoSubstancias");
   const numeroProcesso = localStorage.getItem("numeroProcesso");
   
   const cpfVitima = localStorage.getItem("cpfVitima");
   const nomeVitima = localStorage.getItem("nomeVitima");
   const telefoneVitima = localStorage.getItem("telefoneVitima");
   const cpfAgressor = localStorage.getItem("cpfAgressor");
   const nomeAgressor = localStorage.getItem("nomeAgressor");
   const telefoneAgressor = localStorage.getItem("telefoneAgressor");
   const redsOrigem = localStorage.getItem("redsOrigem");




   
  let nomevitima = document.getElementById("nomevitima");
  let cpfvitima = document.getElementById("cpfvitima");
  let telefonevitima = document.getElementById("telefonevitima");
  let nomeautor = document.getElementById("nomeautor");
  let cpfautor = document.getElementById("cpfautor");
  let telefoneautor = document.getElementById("telefoneautor");
  let medidaprotetiva = document.getElementById("medidaprotetiva"); 
  let redsorigem = document.getElementById("redsorigem"); 

  
  cpfvitima.value = cpfVitima
  nomevitima.value = nomeVitima
  telefonevitima.value = telefoneVitima
  cpfautor.value = cpfAgressor
  nomeautor.value = nomeAgressor
  telefoneautor.value = telefoneAgressor
  medidaprotetiva.value = numeroProcesso
  redsorigem.value = redsOrigem

  CAMPO01.value = relacaoVitimaAutor
  CAMPO02.value = separados 
  CAMPO03.value = tempoRelacionamento
  CAMPO04.value = tempoSeparacao
  CAMPO05.value = temFilhos
  CAMPO06.value = quantidadeFilhos
  CAMPO07.value = nomesIdadesFilhos
  CAMPO08.value = mpu
  CAMPO09.value = acessoArma
  CAMPO10.value = violenciasPsicologicas
  CAMPO11.value = agressoesFisicas
  CAMPO12.value = agressoesMorais
  CAMPO13.value = agressoesPatrimoniais
  CAMPO14.value = agressoesSexuais
  CAMPO15.value = usoSubstancias
  CAMPO16.value = suicidioAgressor
  CAMPO17.value = filhosPresenciaramViolencia

 if (!relacaoVitimaAutor) {
  CAMPO01.value = "*********";
 } 
 if (!separados) {
  CAMPO02.value = "*********";
 } 
 if (!tempoRelacionamento) {
  CAMPO03.value = "*********";
 } 
 if (!tempoSeparacao) {
  CAMPO04.value = "*********";
} 
if (!temFilhos) {
  CAMPO05.value = "*********";
 } 
 if (!quantidadeFilhos) {
  CAMPO06.value = "*********";
 } 
 if (!nomesIdadesFilhos) {
  CAMPO07.value = "*********";
 } 
 if (!mpu) {
  CAMPO08.value = "*********";
 } 
 if (!acessoArma) {
  CAMPO09.value = "*********";
 } 
 if (!violenciasPsicologicas) {
  CAMPO10.value = "*********";
 } 
 if (!agressoesFisicas) {
  CAMPO11.value = "*********";
 } 
 if (!agressoesMorais) {
  CAMPO12.value = "*********";
 } 
 if (!agressoesPatrimoniais) {
  CAMPO13.value = "*********";
 } 
 if (!agressoesSexuais) {
  CAMPO14.value = "*********";
 } 
 if (!usoSubstancias) {
  CAMPO15.value = "*********";
 } 
 if (!suicidioAgressor) {
  CAMPO16.value = "*********";
 } 
 if (!filhosPresenciaramViolencia) {
  CAMPO17.value = "*********";
 }

  const rgVitima = localStorage.getItem("rgVitima");
  let rgVitimaInput = document.getElementById("rgvitima");
  rgVitimaInput.value = rgVitima

    const rgAgressor = localStorage.getItem("rgAgressor");
  let rgAgressorInput = document.getElementById("rgautor");
  rgAgressorInput.value = rgAgressor


const elementoSeSeparados = document.getElementById("SeSeparados");
const elementoSeTemFilhos = document.getElementById("SeTemFilhos");

if (CAMPO02.value === "Sim") {
  elementoSeSeparados.style.display = "block";
} else {
  elementoSeSeparados.style.display = "none";
}

if (CAMPO05.value === "Não") {
  elementoSeTemFilhos.style.display = "none";
} else {
  elementoSeTemFilhos.style.display = "Block";
}

}
